version: 2
updates:
- package-ecosystem: cargo
  directory: "/wee_alloc"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: spin
    versions:
    - 0.7.0
    - 0.8.0
